# Generated by Django 2.1.7 on 2019-03-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
