# Generated by Django 2.1.7 on 2019-03-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_education_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('weight',)},
        ),
    ]
