# Generated by Django 2.1.7 on 2019-03-18 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
