# Generated by Django 2.1.7 on 2019-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-weight',)},
        ),
        migrations.AddField(
            model_name='project',
            name='weight',
            field=models.IntegerField(default=0, help_text='Affects how projects show up; lighter projects appear first, heavier projects last.'),
        ),
    ]
