# Generated by Django 2.1.7 on 2019-03-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190323_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('weight',)},
        ),
    ]
