# Generated by Django 2.1.7 on 2019-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link_to',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
