# Generated by Django 2.1.7 on 2019-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
