# Generated by Django 2.1.7 on 2019-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_job_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('weight',)},
        ),
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.IntegerField(default=0, help_text='Affects how projects show up; lighter projects appear first, heavier projects last.'),
        ),
    ]
